### ISSUE TITLE
關於 model.to(device) 和 model.cuda() 的差別

### ISSUE THREAD

**Issue by WenChouWu** [2019-dl-training-program/Lab2#1]
請問助教, 要將 tensor 送進去 GPU, 用這兩個方式的差別是什麼？

**Comment by ZmaraXion** [comment]
可以參考下方的issue:
[Is there any difference between x.to(‘cuda’) vs x.cuda()? Which one should I use?](https://discuss.pytorch.org/t/is-there-any-difference-between-x-to-cuda-vs-x-cuda-which-one-should-i-use/20137)

兩者最大不同在於 model.to(device) 可以自由指定要使用哪個裝置(e.g. cpu, cuda:0)，因此較為彈性，但 model.cuda() 則只能指定系統預設的 GPU device，而在實作上，兩者方法都是可行的。

**Comment by WenChouWu** [comment]
Got it, thank you.
