### ISSUE TITLE
ResNet50 在公司機器要跑多久？

### ISSUE THREAD

**Issue by ziyu4huang** [2019-dl-training-program/Lab2#2]
可不可以請問一下跑完一輪  要多久時間？ 
因為我現在 ResNet 50  完一輪 要8個小時 (200 epoch)，不知道合不合理

**Comment by ZmaraXion** [comment]
我的訓練設備為GTX 1080Ti，ResNet50 訓練時間可在 3 小時左右完成(164 epoch)
你可以在程式碼中加入 `torch.backends.cudnn.benchmark = True`
速度應該會提昇
