### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by yuhsien1013** [2019-dl-training-program/Lab2#3]
We have questions for Lab2 

We are adding the sample code for confusion matrix base on your following link

https://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html#sphx-glr-auto-examples-model-selection-plot-confusion-matrix-py

the error is happen, and the error message is
TypeError: only integer scalar arrays can be converted to a scalar index

I have already added 
np.array()
.astype(int)

the error is still exist.
how can I do ?

Please let me know if you have any suggestion.
Thank you very much.

**Comment by ZmaraXion** [comment]
Hello, yuhsien:
你可以直接註解掉這行程式碼 `classes = classes[unique_labels(y_true, y_pred)]`
classes 這個參數代表的是 Label 名稱，可以直接使用下方程式碼
`classes=['airplanes', 'cars', 'birds', 'cats', 'deer', 'dogs', 'frogs', 'horses', 'ships', 'trucks']`

TA. 莊祐銓
