### ISSUE TITLE
How to load classes from DataLoader

### ISSUE THREAD

**Issue by FallwinDs** [2019-dl-training-program/Lab2#4]
前面一題issue，助教的回答是改用pre-defined class
這次的class只有10個所以可以用手打list出來
但若有1000個或更多class的dataset應該不太可能就這樣手打1000個
請問pytorch有什麼方式可以從DataLoader裡面讀出class嗎?
或是要採用其他讀data的方式才可以讀入class?

> Hello, yuhsien:
> 你可以直接註解掉這行程式碼 `classes = classes[unique_labels(y_true, y_pred)]`
> classes 這個參數代表的是 Label 名稱，可以直接使用下方程式碼
> `classes=['airplanes', 'cars', 'birds', 'cats', 'deer', 'dogs', 'frogs', 'horses', 'ships', 'trucks']`
> 
> TA. 莊祐銓

**Comment by AlwaysJohn** [comment]
可以使用dataset下的class_to_index這個member來取得class名稱，如下:
![image](https://user-images.githubusercontent.com/12167340/63631533-a55a6880-c65b-11e9-9b66-b78a0fdfdaef.png)

TA
