### ISSUE TITLE
Vanilla train不起來

### ISSUE THREAD

**Issue by xtomho** [2019-dl-training-program/Lab2#6]
助教好，

請問我Vanilla18跟50都會train不起來，accuracy停在10%上不去。Resnet18跟50都train的很正常，accuracy可以到91%。

應該只差在拿掉shortcut，請問這樣要怎麼辦? 謝謝。

        def forward(self, x):
            out = F.relu(self.bn1(self.conv1(x)))
            out = self.bn2(self.conv2(out))
            if **gEnableShortcut**:
                **out += self.shortcut(x)**
            out = F.relu(out)
            return out

**Comment by ZmaraXion** [comment]
你好:

透過你提供的片段，並無發現明顯的錯誤。若ResNet18跟50都可正常運行，理論上整體程式碼應該是合理的，只不過Vanilla18跟50在我這邊仍然可正常訓練，可能問題是出在別的環節。

TA. 莊祐銓
